name: genq
description: Annotations for the genq code generator. 
version: 0.2.0
repository: https://github.com/jankuss/genq

environment:
  sdk: ^3.2.3

# Add regular dependencies here.
dependencies:
  collection: ^1.18.0

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
